### ISSUE TITLE
CombinationGenerator not working?

### ISSUE THREAD

**Issue by ScottChapman** [dwdyer/uncommons-maths#4]
I am wanting to generate all combinations of a set of Booleans. So I did the following:
        ArrayList<Boolean> array = new ArrayList<Boolean>();
        array.add(true);
        array.add(false);
        CombinationGenerator<Boolean> comb = new CombinationGenerator<Boolean>(array,3);

It throws an exception saying Combination length cannot be greater than set size.

**Comment by dwdyer** [comment]
If there are only two items, the maximum combination length is 2 as each item can only occur in each combination once.  Your example code tries to use a length of 3 with only 2 items.
