### ISSUE TITLE
Undocumented behavior: Ignoring setSeed

### ISSUE THREAD

**Issue by etremel** [dwdyer/uncommons-maths#6]
It seems like the uncommons-maths random number generators (i.e. `MersenneTwisterRNG`), although they extend Java's `Random`, do not properly implement the `setSeed` method specified in `Random`'s API. This method specifies that it resets the state of the random number generator to an initial state with the given seed, so calling it with the same seed that the generator was constructed with should make the generator repeat its sequence of random numbers. However, if I attempt to use it to "reset" a `MersenneTwisterRNG`, the random numbers generated do not repeat. Here's a short example of what I'm talking about:

``` java
BigInteger element = new BigInteger("1763540354853708019");
byte[] salt = new byte[2];
Random javaRandom = new Random();
//The following three printlns show the exact same byte sequence each time:
javaRandom.setSeed(element.longValue());
javaRandom.nextBytes(salt);
System.out.println("Bytes generated: " + Arrays.toString(salt));
javaRandom.setSeed(element.longValue());
javaRandom.nextBytes(salt);
System.out.println("Bytes generated: " + Arrays.toString(salt));
javaRandom.setSeed(element.longValue());
javaRandom.nextBytes(salt);
System.out.println("Bytes generated: " + Arrays.toString(salt));
MersenneTwisterRNG random = new MersenneTwisterRNG();
//The following three printlns show a different byte sequence each time
random.setSeed(element.longValue());
random.nextBytes(salt);
System.out.println("Bytes generated: " + Arrays.toString(salt));
random.setSeed(element.longValue());
random.nextBytes(salt);
System.out.println("Bytes generated: " + Arrays.toString(salt));
random.setSeed(element.longValue());
random.nextBytes(salt);
System.out.println("Bytes generated: " + Arrays.toString(salt));
```

This behavior may be an intentional design decision, since the `setSeed` method can only take a `long` and not an arbitrary byte array, and thus could not be used to reset the seed of an RNG that was created with a 128-bit seed. However, it is not documented anywhere in the uncommons-maths documentation, leaving me to figure out by trial and error why my code wasn't working as expected. 

Could someone either fix this bug or document that uncommons-maths' RNGs deviate from the `java.util.Random` contract?

**Comment by dwdyer** [comment]
I will update the documentation.  I'm undecided on whether setSeed should perhaps throw UnsupportedOperationException for RNGs that don't (can't) support it.  Any preference?

**Comment by dwdyer** [comment]
Having tried to over-ride setSeed to throw UnsupportedOperationException, I've realised it's not possible.  All of the RNGs extend from java.util.Random and the default constructor of that class invokes setSeed, so over-riding it to throw an exception breaks everything.

I think we'll have to settle for documenting the issue.

**Comment by etremel** [comment]
OK, I didn't know an UnsupportedOperationException would break things. I do think it would help if the behavior was documented, so that if I try to use setSeed the Javadoc tooltip in my IDE will remind me that this does nothing for MersenneTwisterRNG.

**Comment by AlyoshaVasilieva** [comment]
MersenneTwisterRNG and any others which do not support `setSeed(long)` should override it, delegate to the superclass, and mark it as `@Deprecated`. This way anyone attempting to use that method will have a clear warning not to do so. Assuming they are using an IDE/paying attention.

**Comment by dwdyer** [comment]
@AlyoshaVasilieva Yes, that seems like a sensible approach.
