### ISSUE TITLE
SecureRandomSeedGenerator should not claim to throw exception

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [dwdyer/uncommons-maths#7]
Currently, `SecureRandomSeedGenerator` has this method signature:

`public byte[] generateSeed(int length) throws SeedException`

However, it is impossible for SeedException to be thrown from this method. It therefore shouldn't be declared as being possible.

(Note: removing it will break compatibility of any code directly using that method with that class)

**Comment by dwdyer** [comment]
The throws list is declared by the `SeedGenerator` interface. Yes, technically this particular implementation does not need to declare that it throws the exception and probably shouldn't have when it was originally written but I see no benefit in changing it now. The library code only ever invokes the method via the interface and there is not really any need for non-library code to invoke the method. Though if it does, changing it might potentially break other people's code as you mention.

The implementation of `generateSeed` in `SecureRandomSeedGenerator` is a single line. If you don't need to use the interface to support interchangeable `SeedGenerator` implementations, you might as well just bypass `SecureRandomSeedGenerator` completely and just invoke `SecureRandom.generateSeed` directly.
